### ISSUE TITLE
But Time can go backward too!

### ISSUE THREAD

**Issue by bangzek** [coder/quartz#3]
If the system time is changed to go backward and it's hard to make your go program to handle this case correctly but it can be done.

Idk if it's a good idea to add to quartz cause I haven't unit test my code that handle backward time. I detect time goes backward or jump around by comparing “monotonic clock” and “wall clock” of two time.

**Comment by spikecurtis** [comment]
Yeah, it is possible for wall time to go backward. To keep things simple Quartz assumes that wall time and monotonic time proceed in lockstep.  It might be possible to extend Quartz's API to allow you to change the wall time independent of the monotonic time in testing.  

Can you describe an example use case or unit test you'd like to be able to perform? I feel like that would help in figuring out the right API for it.

**Comment by Emyrk** [comment]
It get's even more tricky...

https://pkg.go.dev/time#hdr-Monotonic_Clocks

> For example, this code always computes a positive elapsed time of approximately 20 milliseconds, even if the wall clock is changed during the operation being timed:

```golang
start := time.Now()
... operation that takes 20 milliseconds ...
t := time.Now()
elapsed := t.Sub(start)
```
> Other idioms, such as [time.Since](https://pkg.go.dev/time#Since)(start), [time.Until](https://pkg.go.dev/time#Until)(deadline), and time.Now().Before(deadline), are similarly robust against wall clock resets.

So time can go backwards, but not for measuring time.

**Comment by spikecurtis** [comment]
@Emyrk that's true if both times have a monotonic clock reading.

> If Times t and u both contain monotonic clock readings, the operations t.After(u), t.Before(u), t.Equal(u), t.Compare(u), and t.Sub(u) are carried out using the monotonic clock readings alone, ignoring the wall clock readings. If either t or u contains no monotonic clock reading, these operations fall back to using the wall clock readings.

For example, when we pull times from the database, it won't have a monotonic clock reading.  If you're not careful, you can still have code that gets broken by a wall time reset.

```
if workspace.StoppedAt.Before(time.Now()) {
  x := someComputationThatBreaksForFutureTimes(workspace.StoppedAt)
}
```

Best case, you just get some slightly nonsensical result, like computing negative dollars or whatever, but the computation could panic and crash your system.  You can usually defend against this kind of thing by ensuring you query `time.Now()` only once, but there are cases where that is hard/awkward.

**Comment by Emyrk** [comment]
That makes sense 👍. Just wanted to add that quartz would have to match the behavior of `time.Time`.

**Comment by spikecurtis** [comment]
Closing as we haven't received an example use case. @bangzek feel free to reopen with some more information if you're interested in pursuing this.
