### ISSUE TITLE
This is cool!

### ISSUE THREAD

**Issue by ghostsquad** [coder/quartz#4]
Looks like a potentially better implementation than mine: https://github.com/ghostsquad/go-timejumper

I never ended up implementing timer/ticker, and was trying to do that this weekend.

One situation I came up with is this:

```go
func DoWithBackoff(dur time.Duration) error {
	err := Do()
	if dur > 10 * time.Second
	if err != nil {
		select {
			case <-clock.After(5 *time.Second):
				DoWithBackoff(dur * time.Duration(2)
		}
	}
}
```

Something like this, where if we `Advance` the clock, the timers need to execute, but there needs to be some time (a purposeful race condition if you will) allowed where the calling code can "register" another After (timer).

The "built-in race condition" (like a sleep for 10millseconds) was what hung me up this weekend.

Thoughts?

**Comment by ghostsquad** [comment]
Oh, I'm reading this section of your blog post: Preventing Test Flakes
https://coder.com/blog/introducing-quartz

Which I think might answer my question

**Comment by spikecurtis** [comment]
Quartz handles this by executing timer callbacks / delivery of ticks in a goroutine, then unlocking the Mock mutex after it's triggered all the events in goroutines.  Those events are then free to register additional timers, or do whatever.  Time is only advanced by the test explicitly, and you can use traps to exactly control the ordering of registering timers compared with advancing time.

Does that answer your question?  If not, feel free to reopen with some more detail.

**Comment by ghostsquad** [comment]
So the client, the one that's receiving the clock interface, that needs to tell the clock it's "ok" to advance time via a trap call?

**Comment by spikecurtis** [comment]
No, traps and advancing time are only done in test code via the Mock.

Product code that uses the `Clock` interface just calls the functions the same way it would the standard library `time` package.
